# Generated by Django 3.1.6 on 2021-03-01 08:21

import KHATEND.Randoms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Teacher_Token', models.TextField(default=KHATEND.Randoms.Random_Token, max_length=100, unique=True)),
                ('Teacher_Id', models.CharField(max_length=50, unique=True)),
                ('Teacher_Password', models.CharField(max_length=50)),
                ('Teacher_Email', models.EmailField(max_length=254, unique=True)),
                ('Teacher_Name', models.CharField(default=KHATEND.Randoms.Random_Name, max_length=50)),
                ('Teacher_Description', models.TextField(blank=True, max_length=300)),
                ('Teacher_ProfileImage', models.FileField(blank=True, upload_to='image/')),
                ('Teacher_CreateDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Token_Token', models.TextField(default=KHATEND.Randoms.Random_Token, max_length=100, unique=True)),
                ('Token_Code', models.CharField(default=KHATEND.Randoms.Random_Code, max_length=6)),
                ('Token_IsVerified', models.BooleanField(default=False)),
                ('Token_CreateDate', models.DateTimeField(auto_now=True)),
                ('Token_User_Email', models.EmailField(max_length=254)),
                ('Token_User_Id', models.CharField(max_length=50)),
                ('Token_User_Password', models.CharField(max_length=50)),
            ],
        ),
    ]
