# Generated by Django 3.1.6 on 2021-03-02 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KHATEND', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='Teacher_ProfileImage',
            field=models.FileField(blank=True, default='image/iconfinder_1041_boy_c_2400506.png', upload_to='image/'),
        ),
    ]
